cc_binary(
    name = "main",
    srcs = ["main.cpp"],
)

cc_binary(
    name = "main_minimal",
    srcs = ["main_minimal.cpp"],
    copts = ["-I/home/andi/workspace/code/number_crunching/include"],
)